"""add notification_preferences login_attempts firmware_history

Revision ID: 0abc57c8f7f8
Revises: f90e1feb7429
Create Date: 2026-07-26 15:01:53.862004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abc57c8f7f8'
down_revision: Union[str, Sequence[str], None] = 'f90e1feb7429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmware_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_mac', sa.String(length=17), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('old_version', sa.String(length=100), nullable=True),
    sa.Column('new_version', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firmware_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firmware_history_device_mac'), ['device_mac'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'channel', name='uq_event_channel')
    )
    with op.batch_alter_table('monitored_hosts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('monitor_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'ping'"))
        batch_op.alter_column('check_interval',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(60)'))
        batch_op.alter_column('max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
        batch_op.alter_column('retry_interval',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(30)'))
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('current_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'unknown'"))
        batch_op.alter_column('consecutive_failures',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_checks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_up',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('is_archived',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_archived',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('monitored_hosts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('total_up',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_checks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('consecutive_failures',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('current_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unknown'"))
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('retry_interval',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(30)'))
        batch_op.alter_column('max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
        batch_op.alter_column('check_interval',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(60)'))
        batch_op.alter_column('monitor_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ping'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.drop_table('notification_preferences')
    op.drop_table('login_attempts')
    with op.batch_alter_table('firmware_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firmware_history_device_mac'))

    op.drop_table('firmware_history')
    # ### end Alembic commands ###
